/**
 * Shared types for the device API — the LAN endpoints that the DeskThing
 * (Spotify Car Thing) client talks to.
 *
 * The device hits HTTP endpoints under /api/v1/* on the overlay server, and
 * uses an SSE channel for live state updates. Auth is a long-lived token
 * minted via a 6-digit pair code generated by the desktop UI.
 */

export interface DeviceCatalogSound {
  id: string
  name: string
  category: 'alerts' | 'board'
  emoji?: string
}

export interface DeviceCatalogAction {
  id: string
  name: string
  icon: string
  color: string | null
  type: string
}

export interface DeviceCatalog {
  sounds: DeviceCatalogSound[]
  actions: DeviceCatalogAction[]
  /** Echoed back so the device knows which ilyStream instance it's talking to. */
  serverVersion: string
}

export interface PairCode {
  code: string
  expiresAt: string
}

export interface PairedDevice {
  token: string
  label: string
  createdAt: string
  lastUsed: string | null
}

export interface PairCompleteRequest {
  code: string
  label: string
}

export interface PairCompleteResponse {
  token: string
}
