#include "shader_loader.h"

#include <bgfx/embedded_shader.h>
#include <iostream>

// Precompiled sprite shader bytecode, one array per backend, generated by
// shaders/compile_shaders.ps1 and committed under shaders/generated/. Each
// header is included only when the current platform actually references that
// backend's array in the BGFX_EMBEDDED_SHADER table below, keeping the guards
// here in lock-step with embedded_shader.h so there are never missing symbols.
#if BGFX_PLATFORM_SUPPORTS_DXBC
#include "dx11/vs_sprite.sc.bin.h"
#include "dx11/fs_sprite.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_SPIRV
#include "spv/vs_sprite.sc.bin.h"
#include "spv/fs_sprite.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_GLSL
#include "glsl/vs_sprite.sc.bin.h"
#include "glsl/fs_sprite.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_ESSL
#include "essl/vs_sprite.sc.bin.h"
#include "essl/fs_sprite.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_METAL
#include "mtl/vs_sprite.sc.bin.h"
#include "mtl/fs_sprite.sc.bin.h"
#endif

namespace ily {

static const bgfx::EmbeddedShader s_spriteEmbeddedShaders[] = {
    BGFX_EMBEDDED_SHADER(vs_sprite),
    BGFX_EMBEDDED_SHADER(fs_sprite),
    BGFX_EMBEDDED_SHADER_END()
};

bgfx::ProgramHandle CreateSpriteProgram() {
    const bgfx::RendererType::Enum type = bgfx::getRendererType();

    bgfx::ShaderHandle vsh = bgfx::createEmbeddedShader(s_spriteEmbeddedShaders, type, "vs_sprite");
    bgfx::ShaderHandle fsh = bgfx::createEmbeddedShader(s_spriteEmbeddedShaders, type, "fs_sprite");

    if (!bgfx::isValid(vsh) || !bgfx::isValid(fsh)) {
        std::cerr << "[ShaderLoader] No embedded sprite shader for renderer "
                  << bgfx::getRendererName(type)
                  << ". Regenerate with shaders/compile_shaders.ps1." << std::endl;
        if (bgfx::isValid(vsh)) bgfx::destroy(vsh);
        if (bgfx::isValid(fsh)) bgfx::destroy(fsh);
        return BGFX_INVALID_HANDLE;
    }

    // destroyShaders = true: the program takes ownership and releases the
    // shader handles when it is destroyed.
    bgfx::ProgramHandle program = bgfx::createProgram(vsh, fsh, true);
    if (!bgfx::isValid(program)) {
        std::cerr << "[ShaderLoader] Failed to link sprite program for renderer "
                  << bgfx::getRendererName(type) << std::endl;
    }
    return program;
}

} // namespace ily
